Django/django文档学习/1. 快速入门/Demo/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

Django/django文档学习/1. 快速入门/Demo/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexViews.as_view(), name='index'),
    # 通用视图接受一个 pk 主键作为url的参数
    path('<int:pk>/datail/', views.DetailViews.as_view(), name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/result/', views.ResultViews.as_view(), name='result')
]

Django/django文档学习/1. 快速入门/Demo/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    
    def was_published_recently(self):
        """
        是否是最近一天发布的，可以展示在admin页面
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    # 以下用来美化admin页面的显式
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    # 多对一关系
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django/django文档学习/1. 快速入门/Demo/polls/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
# 通用视图模块
from django.views import generic
from django.utils import timezone

# Create your views here.

class IndexViews(generic.ListView):
    """
    用来渲染一个列表视图
    """
    model = Question
    context_object_name = 'question_list'
    template_name = 'polls/index.html'
    
    # 必须实现这个方法，来约束渲染哪写数据
    def get_queryset(self):
        # pub_date__lte pub_date比当前时间早的
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailViews(generic.DetailView):
    model = Question
    # 声明上下文（render中的那个字典）名
    context_object_name = 'question'
    # 声明作用的模板名
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        只允许查看之前已经发布的
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultViews(generic.DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'polls/result.html'



def vote(request, question_id):
    # 找不到抛出404页面
    question = get_object_or_404(klass=Question, pk=question_id)
    
    choice_list = Choice.objects.filter(question=question)
    
    if request.method == 'POST':
        try:
            get_choice_id = request.POST['choice']
            
        except KeyError:
            context = {
                'error': '请至少选择一项',
                'question': question,
                'choices': choice_list
            }
            return render(request, 'polls/detail.html', context)
        else:
            choice = get_object_or_404(Choice, id=get_choice_id)
            choice.votes += 1
            choice.save()
    
    # 重定向到直到页面，reverse用来构造url，返回str
    return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))

Django/django文档学习/1. 快速入门/Demo/polls/templates/polls/detail.html
<h1>details</h1>
{% if error %}{{error}}{% endif %}
<h2>{{question}}</h2>
{% if question.choice_set.all %}
<table>

<!-- {% for choice in choices %}
<tr>
    <td>{{choice.choice_text}}</td>
    <td>{{choice.votes}}</td>
</tr>
{% endfor %} -->

<form action="{% url 'polls:vote' question.id %}", method='POST'>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="提交">
</form>
</table>
{% else %}
没有选项
{% endif %}

Django/django文档学习/1. 快速入门/Demo/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/index.css' %}">

{% if question_list %}
    {% for question in question_list %}
        <a href="{% url 'polls:detail' question.id %}">{{question}}</a>
        
    {% endfor %}
{% else %}
    没有任何投票
{% endif %}

Django/django文档学习/1. 快速入门/Demo/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>